### ISSUE TITLE
[Question] transition to s6 based init

### ISSUE THREAD

**Issue by ngortheone** [skarnet/s6#21]
Hello @skarnet 

I want to try s6 as my primary init system. I am using Gentoo and Alpine linux

It looks like Gentoo wiki page is outdated, as it refers to 0.4 and 1.0 versions of s6 (while releases show 2.x)
https://wiki.gentoo.org/wiki/S6_and_s6-rc-based_init_system

Do you happen to know of any existing manuals or success stories that describe the process of building s6 based linux system?
Perhaps you can share some of your personal experience. I've read a lot of https://skarnet.org/software/s6/ but what I think is missing is a good "How to get started" guide. 

Maybe there are Linux distributions that are better suited to get started with s6 then others.

Thanks!

**Comment by skarnet** [comment]
I know s6 is hard to get into for lack of tutorials or beginner guides. I'm planning to write a high-level interface that will hopefully make things better.
There are several distributions using s6 one way or another, for instance:
- Obarun (with a set of helper tools known as 66)
- Artix
- Adélie Linux

I suggest starting with one of those.
Alternatively, if you want to do things manually:
- It's pretty easy to use s6 as your init system: you just need to install [s6-linux-init](https://skarnet.org/software/s6-linux-init/) and follow the instructions. That will get you s6-svscan as process 1, and a sysvinit-compatible interface to shut down the machine. It can be a drop-in replacement for a sysvinit-based system, you can easily do that on Gentoo or Alpine.
- What is more complex is switching service managers. Gentoo and Alpine are using OpenRC. It's easy to use s6 as an init system while keeping OpenRC as your service manager; this is for instance what Adélie Linux is doing. But replacing OpenRC with s6-rc is a lot more work. Obarun and Artix have done a good job, but since _every_ service needs to be converted, there is always more to do.

My advice is to start with s6-linux-init so you can have a supervision tree at all times and s6 as process 1, and you can play with it; then, if you're motivated, you can start having a go at s6-rc. Note that a new version of s6-rc is planned for 2021, which should make it easier to provide a user-friendly interface.

Also, come to #s6 on Freenode IRC, you'll be able to interact with a lot of people who have gone through this journey already and will be able to help you and give you pointers!

**Comment by skarnet** [comment]
Can I close this?

**Comment by ngortheone** [comment]
Sure, sorry!
