### ISSUE TITLE
s6-log: log retention duration

### ISSUE THREAD

**Issue by oliverpool** [skarnet/s6#36]
With the GDPR (RGPD in french) the logging policy must be stated in terms of retention duration (especially when they might contain personal data, like an IP address).

Currently s6-log does not seem to have the ability to enforce a policy like: keep the logs for at most 90 days.

---

It would probably needs to articulate around 2 settings:
- `max_retention`: logdirs should contain only archived files newer than a given time (e.g. 89 days)
- `autorotate_duration`: rotate the log after a given time (e.g. 1 day)

This last setting is necessary if a service does not log much, its timespan must be added to the `max_retention` duration (if a log contains 10 days of data, then the logs will be actually kept for 89+10= 99 days).

What do you think?

**Comment by skarnet** [comment]
- s6-log provides mechanism, not policy.
- s6-log's goals include making sure you do not lose data (for instance by accidentally running out of disk space). They do not include making sure you lose data. I am sympathetic to the GDPR, but s6-log is an admin tool that is focused on getting the information safely written to disk. What happens if you *do not* want the information is none of its concern.
- Implementing policy such as the one mandated by the GDPR can be done with a simple additional service, e.g. in a daily crontab:
  * if the `current` file is older than 90 days, trigger a rotation (`s6-svc -a logger_service`)
  * for every archived file (`@*.s` and `@*.u`), if they're older than 90 days, delete it.
- For any discussion about s6, please use the [supervision mailing-list](https://skarnet.org/lists/#supervision), not GitHub. 😉

**Comment by oliverpool** [comment]
Thank you for the quick reply and the pointers on how I should achieve this. I will give it a try!

To prevent such issues, you might be interested in setting up [github issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) (PR example, where I proposed it on another repo: https://github.com/spdx/license-list-XML/pull/1771#issuecomment-1429313878).
