### ISSUE TITLE
Allow s6-svscan to handle more signals

### ISSUE THREAD

**Issue by gtbuchanan** [skarnet/s6#5]
I can't seem to get `s6-svscan -s` to divert signals such as `SIGPWR` and `SIGRTMIN+3` on Alpine. Creating `/etc/s6/services/.s6-svscan/SIGPWR` or `SIGRTMIN+3` don't appear to have an effect. I even tried `SIG???` since `sig_name` returns `???` when it can't determine the name, but that doesn't work either for whatever reason. Presumably `child_spawn0` doesn't like the question marks.

Obviously, the [docs](https://skarnet.org/software/s6/s6-svscan.html) don't mention this is possible since there is an explicit list of supported signals. All of the diverted signals listed in the docs work fine. However, it would be nice to be able to handle other signals even if they're not defined in `sig_table` and/or don't have a defined constant.

The primary reason for wanting `SIGRTMIN+3` is for handling the [`lxc-stop`](https://github.com/lxc/lxc/pull/1086) command gracefully without having to set `lxc.signal.halt` to something else.

Perhaps `s6-svscan` could fall back to using the signal number when searching for the handler script if `sig_name` returns `???`, or supporting both name and number?

**Comment by skarnet** [comment]
It's not only about looking for a handler script when a signal arrives. `s6-svscan` has to explicitly catch the signal first. That's why you couldn't make `SIG???` work - the signals you wanted are simply not caught.

There's no major theoretical objection to what you want, but there _are_ a few practical ones, that makes catching each and every signal very difficult to do portably. One of them is that there is an implementation-defined set of signals you just cannot trap, and on some systems `sigaction()` fails, and making sure the failure is due to an uncatchable signal and not a kernel issue is a problem that requires either _a lot_ of code, or `#ifdef` mazes, to be solved correctly. Other issues are, for instance, how to establish a bijection between a signal such as `SIGRTMIN+3` and its handler script for an (almost) arbitrarily large number of signals, without breaking compatibility with existing names, and without being entirely counter-intuitive (`SIG13`, `SIG14`, `SIGTERM`, `SIG16`, what?)

`s6-svscan` aims to be portable, and is a very critical piece of code, so I want to keep it as simple as possible. I had already thought about generalizing the signal diversion mechanism, but in the end the benefits aren't worth the amount of code and complexity that it would add. I'm sorry. You'll end up with much less complexity on your system by just setting `lxc.signal.halt`. :-)

**Comment by gtbuchanan** [comment]
No worries. Thought it couldn't hurt to ask :) I figured it was something more complex than I was aware of in my limited C knowledge. I'm developing some generic LXC images and I was trying to avoid having to tell people to always set `lxc.signal.halt`, but sounds like that's the easiest solution. Thank you for the detailed explanation!
